spring:
  profiles:
    active: dev
application:
  security:
    jwt:
      secret-key: ${jwt-secret-pass}
      expiration: 864000000
logging:
  level:
    org:
      springframework:
        security:
          web: DEBUG